services:
    wakeapp_enumer.enumer:
        class: Wakeapp\Component\Enumer\Enumer
        factory: [Wakeapp\EnumerBundle\Factory\EnumerFactory, 'create']
        arguments:
            - '%wakeapp_enumer.enum%'
