services:
    Wakeapp\Bundle\EnumerBundle\Registry\EnumRegistryService:
        public: true
        arguments:
            - []
    wakeapp_enumer.enum_registry:
        public: true
        alias: Wakeapp\Bundle\EnumerBundle\Registry\EnumRegistryService

    Wakeapp\Bundle\EnumerBundle\Doctrine\Connection\ConnectionFactoryDecorator:
        decorates: doctrine.dbal.connection_factory
        decoration_inner_name: doctrine.dbal.connection_factory.inner
        arguments:
            - '@doctrine.dbal.connection_factory.inner'
            - '@Wakeapp\Bundle\EnumerBundle\Registry\EnumRegistryService'

    Wakeapp\Component\DbalEnumType\EventSubscriber\EnumEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
