services:
    MarfaTech\Bundle\EnumerBundle\Registry\EnumRegistryService:
        public: true
        arguments:
            - []
    marfatech_enumer.enum_registry:
        public: true
        alias: MarfaTech\Bundle\EnumerBundle\Registry\EnumRegistryService
